name = "Utils"
uuid = "eba55543-16ed-4224-9835-1cb6206fd75a"
authors = ["Jorge Brito <jorge.brito.xyz@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Match = "1"
MacroTools = "0.5"
Reexport = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
